#!/usr/bin/env python3
# Copyright 2020 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Lint our source files."""

import sys

import kokoro
import libdot


def main(argv):
    """The main func!"""
    return libdot.lint.main(argv, basedir=kokoro.DIR)


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
